export const ROLES = {
  STUDENT: 'student',
  ACADEMIC_ADVISOR: 'academic_advisor',
  FACULTY_ASSISTANT: 'faculty_assistant',
  FACULTY_MANAGER: 'faculty_manager',
  STUDENT_AFFAIRS: 'student_affairs',
  PRINCIPAL: 'principal',
  OFFICE_STAFF: 'office_staff',
  ADMIN: 'admin',
};

export const ROLE_LIST = Object.values(ROLES);

export const PERMISSIONS = {
  SUBMISSION_CREATE: 'submission:create',
  SUBMISSION_VIEW_OWN: 'submission:view:own',
  SUBMISSION_VIEW_ALL: 'submission:view:all',
  WORKFLOW_APPROVE: 'workflow:approve',
  WORKFLOW_REJECT: 'workflow:reject',
  SIGNATURE_SIGN: 'signature:sign',
  USER_MANAGE: 'user:manage',
  REPORT_VIEW: 'report:view',
  AUDIT_VIEW: 'audit:view',
  SETTINGS_MANAGE: 'settings:manage',
};

export const ROLE_PERMISSIONS = {
  [ROLES.STUDENT]: [PERMISSIONS.SUBMISSION_CREATE, PERMISSIONS.SUBMISSION_VIEW_OWN],
  [ROLES.ACADEMIC_ADVISOR]: [PERMISSIONS.WORKFLOW_APPROVE, PERMISSIONS.WORKFLOW_REJECT],
  [ROLES.FACULTY_ASSISTANT]: [PERMISSIONS.WORKFLOW_APPROVE, PERMISSIONS.WORKFLOW_REJECT],
  [ROLES.FACULTY_MANAGER]: [PERMISSIONS.WORKFLOW_APPROVE, PERMISSIONS.REPORT_VIEW],
  [ROLES.STUDENT_AFFAIRS]: [PERMISSIONS.WORKFLOW_APPROVE, PERMISSIONS.REPORT_VIEW],
  [ROLES.PRINCIPAL]: [PERMISSIONS.SIGNATURE_SIGN, PERMISSIONS.WORKFLOW_APPROVE],
  [ROLES.OFFICE_STAFF]: [PERMISSIONS.WORKFLOW_APPROVE, PERMISSIONS.SUBMISSION_VIEW_ALL],
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
};
